gateway:
  hostname: aiopsgw.lb-aws-labs.link
  auth:
    provider: noauth
    noauth:
      grafanaHostname: grafana.lb-aws-labs.link

  persistence:
    enabled: true
    size: 5Gi
    storageClass: gp3
    accessMode: ReadWriteOnce

opni-nats:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp3
    accessMode: ReadWriteOnce

opni-agent:
  kube-prometheus-stack:
    grafana:
      enabled: true

opni-prometheus-crd:
  enabled: false