gateway:
  hostname: aiopsgw.lb-aws-labs.link
  auth:
    provider: noauth
    noauth:
      grafanaHostname: grafana.lb-aws-labs.link
  persistence:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClass: gp3

opni-agent:
  kube-prometheus-stack:
    enabled: true
    grafana:
      enabled: true
      defaultDashboardsEnabled: true

opni-prometheus-crd:
  enabled: false

opni-nats:
  persistence:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClass: gp3